variable "vpc_cidr_block" {}
variable "tags" {}
variable "env" {}
variable "public_subnet" {}
variable "web_subnet" {}
variable "app_subnet" {}
variable "db_subnet" {}
variable "availability_zone" {}
variable "account_id" {}
variable "default_vpc_id" {}
variable "default_route_table_id" {}
variable "backend" {}
variable "bastion_workstation_cidr" {}
variable "default_vpc_cidr" {}